server:
  port: 8080
spring: 
  application: 
    name: eureka-client #ribbon调用时会用到
eureka: 
  client: 
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://eureka01:8081/eureka/,http://eureka02:8082/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: eureka-client #指定实例id
