server: 
  port: 8082 #服务端口
spring: 
  application: 
    name: eureka-server
eureka: 
  client: 
    register-with-eureka: true #服务注册,是否注册到eureka服务中
    fetch-registry: true #服务发现,是否从eureka中获取注册信息
    service-url: 
        defaultZone: http://eureka01:8081/eureka/ #状态上报地址,写对方地址,多个节点用逗号隔开
  server: 
    enable-self-preservation: true #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000  #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance: 
    hostname: eureka02